### ISSUE TITLE
Doesnt save nothing on /Downloads

### ISSUE THREAD

**Issue by ghost** [Halfeld/recordall#2]
Hi, for some reason the record does not throw any output on save. Tested on Chromium on raspberry pi 3.

**Comment by IgorHalfeld** [comment]
@Askmewho Hmm... This is weird! Is there any notification that the video is saved?

**Comment by ghost** [comment]
Yes, it does. But I search everywhere!

**Comment by IgorHalfeld** [comment]
I don't tried out on raspberry, maybe on the `root` diretory... xD
